scripts/dtc: Remove redundant YYLOC global declaration
commit e33a814e772cdc36436c8c188d8c42d019fda639
upstream.

Signed-off-by: tomyprs <tomy.prs25@gmail.com>
gcc 10 will default to -fno-common, which
causes this error at link time:# Please enter
the commit message for your changes. Lines
starting
  (.text+0x0): multiple definition of `yylloc';
  dtc-lexer.lex.o (symbol from
  plugin):(.text+0x0): first defined here#
This is because both dtc-lexer as well as
dtc-parser define the same# (use "git pull" to
merge the remote branch into yours) global
symbol yyloc. Before with -fcommon those were
merged into one# defintion. The proper solution
would be to to mark this as "extern",# Changes
to be committed: however that leads to:#
modified: scripts/dtc-aosp/dtc/dtc-lexer.l
  dtc-lexer.l:26:16: error: redundant
  redeclaration of 'yylloc'
  [-Werror=redundant-decls]
   26 | extern YYLTYPE yylloc;
      |                ^~~~~~
In file included from dtc-lexer.l:24:
dtc-parser.tab.h:127:16: note: previous
declaration of 'yylloc' was here
  127 | extern YYLTYPE yylloc;
      |                ^~~~~~
cc1: all warnings being treated as errors which
means the declaration is completely redundant
and can just be dropped. Signed-off-by: Dirk
Mueller <dmueller@suse.com> Signed-off-by:
David Gibson <david@gibson.dropbear.id.au>
[robh: cherry-pick from upstream] Cc:
stable@vger.kernel.org Signed-off-by: Rob
Herring <robh@kernel.org> [nc: Also apply to
dtc-lexer.lex.c_shipped due to a lack of
     e039139be8c2, where dtc-lexer.l started
     being used]
Signed-off-by: Nathan Chancellor
<natechancellor@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>